config/routes.rb
Rails.application.routes.draw do

  resources :photos

  resources :events

  resources :tags

  resources :comments

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :commentable, polymorphic: true
end

app/models/event.rb
class Event < ActiveRecord::Base
	has_many :photos
	has_many :comments, as: :commentable
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	# attr_reader :gallery_id, :name, :image, :remote_image_url
	belongs_to :event
	has_and_belongs_to_many :tags
	mount_uploader :image, ImageUploader

	has_many :comments, as: :commentable
	accepts_nested_attributes_for :comments

	scope :past_week, -> { where('date > ?', 1.week.ago)}
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_and_belongs_to_many :events
	has_and_belongs_to_many :photos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def index
		@comments = Comment.all
	end

	def show
		@comment = Comment.find(params[:id])
	end


	def new
		@new_comment = Comment.new
	end

	def create
		@new_comment = Comment.where(comment_params).first_or_create
		if @new_comment.save
			redirect_to :back
		else
			redirect_to new_comment_path
		end
	end


	def edit
		@comment = Comment.find(params[:id])
	end

	def update
		@comment = Comment.find(params[:id])
		if @comment.update_attributes(params[:id])
			redirect_to comments_path
		else
			redirect_to comment_path
		end
	end


	def destroy
		@comment = Comment.find(params[:id])
		if @comment.destroy
			redirect_to comments_path
		else
			redirect_to comment_path
		end
	end

	private

	def comment_params
		params.require(:comment).permit(:commentable_id, :commentable_type, :content)
	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	def index
		@events = Event.all
	end

	def show
		@event = Event.find(params[:id])
	end


	def new
		@new_event = Event.new
	end

	def create
		@new_event = Event.new(event_params)
		if @new_event.save
			redirect_to events_path
		else
			redirect_to event_path
		end
	end


	def edit
		@event = Event.find(params[:id])
	end

	def update
		@event = Event.find(params[:id])
		if @event.update_attributes(event_params)
			redirect_to events_path
		else
			redirect_to event_path
		end
	end


	def destroy
		@event = Event.find(params[:id])
		if @event.destroy
			redirect_to events_path
		else
			redirect_to event_path
		end
	end

	private

	def event_params
		params.require(:event).permit(:name, :date, :created_at, :updated_at)
	end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

	def index
		@photos = Photo.all
	end

	def show
		@photo = Photo.find(params[:id])
		@new_tag = @photo.tags.build
		@new_comment = @photo.comments.build
	end


	def new
		@new_photo = Photo.new(event_id: params[:event_id])
	end

	def create
		@new_photo = Photo.new(photo_params)
		if @new_photo.save
			redirect_to photos_path
		else
			redirect_to photo_path
		end
	end


	def edit
		@photo = Photo.find(params[:id]) #just finds it and shows it on webpage
		@new_tag = @photo.tags.build
		@new_comment = @photo.comments.build#(commentable_type: "Photo")
	end

	def update
		@photo = Photo.find(params[:id])
		if @photo.update_attributes(photo_params)
		# if @photo.tags.update_attributes(params[:id])
			redirect_to photos_path
		else
			redirect_to photos_path
		end
	end


	def destroy
		@photo = Photo.find(params[:id])
		if @photo.destroy
			redirect_to photos_path
		else
			redirect_to photo_path
		end
	end



	private

	def photo_params
		# params.require(:photo).permit!
		params.require(:photo).permit(:photo_name, :date, :image, comments_attributes:[:content])
		# params.permit(:photo, :name, comments_attributes:[:content])
	end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	def index
		@tags = Tag.all
	end

	def show
		@tag = Tag.find(params[:id])
	end


	def new
		@new_tag = Tag.new
	end

	def create
		@new_tag = Tag.where(tag_params).first_or_create
		@photo = Photo.find(params[:photo_id])
		if @new_tag.save
			@photo.tags << @new_tag unless @photo.tags.exists?(@new_tag)
			redirect_to :back
		else
			redirect_to new_tag_path
		end
	end


	def edit
		@tag = Tag.find(params[:id])
	end

	def update
		@tag = Tag.find(params[:id])
		if @tag.update_attributes(params[:id])
			redirect_to tags_path
		else
			redirect_to tag_path
		end
	end


	def destroy
		@tag = Tag.find(params[:id])
		if @tag.destroy
			redirect_to tags_path
		else
			redirect_to tag_path
		end
	end

	private

	def tag_params
		params.require(:tag).permit(:name)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/comments/index.html.haml
index.html.haml

app/views/events/edit.html.haml
= form_for @event do |e|
	= e.label "Event name"
	= e.text_field :name
	%br
	= e.label :date
	= e.date_select :date
	%br
	= e.submit "Edit"

app/views/events/index.html.haml
- @events.each do |e|
	= e.name
	= e.date
	- e.photos.each do |p|
		= p.photo_name
	= link_to "Edit event ", edit_event_path(e)
	= link_to "See photos", event_path(e)
	= link_to "Delete event", e, method: :delete, data: { confirm: "Are you absolutely sure?" }
	%br

= link_to "Create a new event", new_event_path

app/views/events/new.html.haml
= form_for @new_event do |e|
	= e.label :name
	= e.text_field :name
	%br
	= e.label :date
	= e.date_select :date
	%br
	= e.submit "Create"

app/views/events/show.html.haml
/ = form_for @new_photo, url: photos_path, method: :post, :html => {:multipart => true} do |p|
/ 	= p.label "Photo name"
/ 	= p.text_field :name
/ 	%br
/ 	= p.label "Date"
/ 	= p.date_select :date
/ 	%br
/ 	= p.file_field :image
/ 	%br
/ 	= p.submit "Add a new photo"


- @event.photos.each do |p|
	= image_tag p.image_url(:thumb).to_s
	= p.photo_name
	= link_to "Edit picture", edit_photo_path(p)
	= link_to "Delete picture", p, data: { confirm: "Are you sure you want to delete this picture?" }, method: "delete"
	= link_to "View picture", photo_path(p)
		
= link_to "Add new photo", new_photo_path(event_id: @event.id)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhotosAndEventsApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>



</head>
<body>

<%= yield %>

</body>
</html>

app/views/photos/edit.html.haml
= form_for @photo, :html => {:multipart => true} do |p|
	= p.label "Photo name"
	= p.text_field :photo_name
	%br
	= p.label "Date"
	= p.date_select :date
	%br
	= p.file_field :image
	%br
	= p.submit "Add a new photo"

app/views/photos/index.html.haml
%table
	.thead
	- @photos.each do |p|
		%tr
			%th= "Name"
			%th= "Date taken"
			%th= "Tags"
		%tr
			%td= p.photo_name
			%td= p.date
			- p.tags.each do |t|
				%td= t.name
			- p.comments.each do |c|
				%td= c.content
			%td= button_to "Edit", edit_photo_path(p), method: "get"
			%td= button_to "Delete", p, method: "delete", data: { confirm: "Are you sure?" }
		%tr
			%td= image_tag p.image_url(:thumb).to_s

= link_to "Add Photo", new_photo_path


	

app/views/photos/new.html.haml
= form_for @new_photo, :html => {:multipart => true} do |p|
	= p.text_field :event_id
	= p.label "Photo name"
	= p.text_field :photo_name
	%br
	= p.label "Date"
	= p.date_select :date
	%br
	= p.file_field :image
	%br
	= p.submit "Add a new photo"

app/views/photos/scratch_code.html.haml
	//- p.tags.each do |x|
			//%td= x.name

photo.tags.each do |x|
	%td= x.name

- i = Tag.first
	= f.tags << i

app/views/photos/show.html.haml
%table
	.thead
		%tr
			%th= "Name"
			%th= "Date taken"
			%th= "Tags"
			%th= "Comments"
		%tr
			%td= @photo.photo_name
			%td= @photo.date
			- @photo.tags.each do |t|
				%td= t.name
			%br
			- @photo.comments.each do |c|
				%td= c.content
			%td= button_to "Edit", edit_photo_path(@photo), method: "get"
			%td= button_to "Delete", @photo, method: "delete", data: { confirm: "Are you sure?" }
		%tr
			%td= image_tag @photo.image_url.to_s


= form_for @new_tag, url: tags_path, method: :post do |t| #transfer this over to tags folder?? (need delete option for tags just on this page)
	= t.label "Any tags?"
	= t.text_field :name
	= hidden_field_tag :photo_id, @photo.id
	= t.submit "Click to tag"

%br

= form_for @new_comment, method: :post do |c|
	= c.hidden_field :commentable_id, value: @new_comment.commentable_id
	= c.hidden_field :commentable_type, value: @new_comment.commentable_type
	= c.text_field :content

	= c.submit "Leave a comment", class: "btn btn-info"